# Welcome to gait!

# Hover over the "AI Git-blame" on the right to see the prompt that generated this function!
# We used an Inline Chat to do this
def print_inline_chat_message():
    print("This is a function generated by an Inline Chat")


# Hover over the "AI Git-blame" on the right to see the prompt that generated this function!
# We used a Panel Chat to do this
def print_panel_chat_message():
    print("This is a function generated by a Panel Chat")


# Gait will track these automatically, no need for any work on your part!

# You should see the both chats in the Gait Panel

# Here, you can choose which prompts you want to stage/unstage, much like git!

# You can also continue off of conversations you've had before, just click the "Continue" button!


